# Generated by Django 5.0.6 on 2026-09-20 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(help_text='Include country code, e.g. +9198XXXXXXXX', max_length=20)),
                ('village', models.CharField(blank=True, max_length=120)),
                ('preferred_language', models.CharField(default='Hindi', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('tool', 'Tool'), ('produce', 'Harvested Produce')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('low_stock_threshold', models.FloatField(default=5)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='farm.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farm.farmer')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.inventoryitem')),
            ],
        ),
    ]
