from django.db import models
from django.utils import timezone
import datetime


class Farmer(models.Model):
    """Hour 0.5: core farmer profile — everything else links back to this."""
    name = models.CharField(max_length=120)
    phone = models.CharField(max_length=20, help_text="Include country code, e.g. +9198XXXXXXXX")
    village = models.CharField(max_length=120, blank=True)
    preferred_language = models.CharField(max_length=30, default="Hindi")

    def __str__(self):
        return self.name


class InventoryItem(models.Model):
    """Hour 0.5-2: Inventory Management + Expiry Tracking feature."""
    CATEGORY_CHOICES = [
        ("seed", "Seed"),
        ("fertilizer", "Fertilizer"),
        ("tool", "Tool"),
        ("produce", "Harvested Produce"),
    ]
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, related_name="inventory")
    name = models.CharField(max_length=120)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    quantity = models.FloatField()
    unit = models.CharField(max_length=20, default="kg")
    low_stock_threshold = models.FloatField(default=5)
    expiry_date = models.DateField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def is_low_stock(self):
        return self.quantity <= self.low_stock_threshold

    @property
    def days_to_expiry(self):
        if not self.expiry_date:
            return None
        return (self.expiry_date - timezone.now().date()).days

    @property
    def is_expiring_soon(self):
        d = self.days_to_expiry
        return d is not None and 0 <= d <= 5

    def __str__(self):
        return f"{self.name} ({self.quantity}{self.unit}) - {self.farmer.name}"


class Alert(models.Model):
    """Hour 2-3.5: generated by the alert checker, then (optionally) sent via SMS/WhatsApp."""
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE, related_name="alerts")
    item = models.ForeignKey(InventoryItem, on_delete=models.CASCADE, null=True, blank=True)
    message = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    sent = models.BooleanField(default=False)

    def __str__(self):
        return self.message
